function parameter_list = p2_organise_parameters(parameters)
    %% Organise the parameters in to a more presentable format
    parameter_list = struct(...
        "hunger_per_m", parameters.needs.hunger_per_m,...
        "flight_distance_per_day", parameters.needs.flight_distance_per_day, ...
        "days_without_nourishment", parameters.needs.days_without_nourishment, ...
        "days_without_social", parameters.needs.days_without_social, ...
        "days_without_environment", parameters.needs.days_without_environment, ...
        "socialising_min_distance", parameters.needs.min_distances.socialising_min_distance, ...
        "breeding_min_distance", parameters.needs.min_distances.breeding_min_distance,...
        "park_min_distance", parameters.needs.min_distances.park_min_distance,...
        "food_min_distance", parameters.needs.min_distances.food_min_distance,...
        "nourishment_booster", parameters.needs.boosters.nourishment, ...
        "environment_booster", parameters.needs.boosters.environment, ...
        "critical_nourishment", parameters.needs.criticals.nourishment,...
        "critical_social", parameters.needs.criticals.social,...
        "critical_environment", parameters.needs.criticals.environment,...
        "breeding_success_per_nourishment", parameters.life.breeding_success_per_nourishment, ...
        "nourishment_per_sq_m2", parameters.scalers.nourishment_per_sq_m2 ...
    );
end